mongodb_params:
  mongodb_cred_filename: mongodb_credentials.yaml
  col_name: 'tweets_miscarriage_all_wo_reply'

research_params:
  # yaml_key: search_tweets_v2
  twitter_cred_filename: twittercredentials.yaml
  max_tweets: 100000
  results_per_call: 500
  date: ['14-10-2021', '15-10-2021', '16-10-2021', '27-09-2021', '28-09-2021', '29-09-2021', '14-10-2022', '15-10-2022', '16-10-2022', '27-09-2022', '28-09-2022', '29-09-2022']
  days_before: 0
  days_after: 0
  since_id: null
  # since_id: '1575199451903594497'
  query: ['miscarriage', 'abortion', 'feticide', 'foeticide', 'aborticide',
          'stillbirth', '"early pregnancy loss"', '"fetal homicide"', '"child destruction"']
  # additional_query: ['-is:retweet']
  additional_query: ['-is:retweet', '-is:reply']
  expansions: ['geo.place_id','attachments.media_keys', 'referenced_tweets.id', 'author_id']
  tweet_fields: ["author_id", "conversation_id", "in_reply_to_user_id", 'attachments',
              "referenced_tweets", "created_at", "geo", "id", "lang", "public_metrics", "text"]
  user_fields: ['username', 'created_at', 'location']
  media_fields: ['type', 'url']
  place_fields: ['country', 'full_name']
  granularity: null
  output_format: a
  stringify: true
