mongodb_params:
  mongodb_cred_filename: mongodb_credentials.yaml
  col_name: 'tweets_miscarriage_2022_bis'

research_params:
  # yaml_key: search_tweets_v2
  twitter_cred_filename: twittercredentials.yaml
  max_tweets: 100000
  results_per_call: 500
  date: '28-09-2022'
  days_before: 1
  days_after: 1
  since_id: null
  # since_id: '1575199451903594497'
  query: ['msicarriage', 'abortion', 'termination', 'feticide', 'foeticide', 'aborticide',
          'stillbirth', '"early pregnancy loss"', '"fetal homicide"', '"child destruction"']
  expansions: ['geo.place_id','attachments.media_keys', 'referenced_tweets.id']
  tweet_fields: ["author_id", "conversation_id", "in_reply_to_user_id", 'attachments',
              "referenced_tweets", "created_at", "geo", "id", "lang", "public_metrics", "text"]
  user_fields: []
  media_fields: ['type', 'url']
  place_fields: ['country', 'full_name']
  granularity: null
  output_format: a
  stringify: true
